package org.example.model;

import jakarta.persistence.*;
import org.example.ProductManagementFacade;

/**
 * Represents a product entity in the Mini-Shopify system.
 * This class is mapped to a database table and contains product information.
 * Note: This is a stub implementation to support ShopManagementFacade and has not been fully implemented yet.
 */
@Entity
public class Product {
dpkmadkmap
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int productID; // Primary key, automatically generated by database

    @Column(name = "product_name")
    private String productName; // Name of the product

    @Column(name = "product_desc")
    private String productDescription; // Description of the product

    @Column(name = "product_cost")
    private double productPrice; // Price of the product

    @Column(name = "product_category")
    private String productCategory; // Category the product belongs to

    @Column(name = "product_quantity")
    private int quantity; // Available quantity in inventory

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "facade_id")
    private Shop shop; // Many-to-one relationship with Shop entity

    /**
     * Default constructor required by JPA.
     */
    public Product() {}

    /**
     * Constructs a new Product with specified details.
     * @param productName the name of the product
     * @param productDescription the description of the product
     * @param productPrice the price of the product
     * @param productCategory the category of the product
     * @param quantity the available quantity
     * @param shop the shop that owns this product
     */
    public Product(String productName, String productDescription, double productPrice, String productCategory, int quantity, Shop shop) {
        this.productName = productName;
        this.productDescription = productDescription;
        this.productPrice = productPrice;
        this.productCategory = productCategory;
        this.quantity = quantity;
        this.shop = shop;
    }

    // GETTER METHODS

    /**
     * Gets the product name.
     * @return the product name
     */
    public String getProductName() {
        return productName;
    }

    /**
     * Gets the product description.
     * @return the product description
     */
    public String getProductDescription() {
        return productDescription;
    }

    /**
     * Gets the product price.
     * @return the product price
     */
    public double getProductPrice() {
        return productPrice;
    }

    /**
     * Gets the product category.
     * @return the product category
     */
    public String getProductCategory() {
        return productCategory;
    }

    /**
     * Gets the product ID.
     * @return the product ID
     */
    public int getProductID() {
        return productID;
    }

    /**
     * Gets the product quantity.
     * @return the available quantity
     */
    public int getQuantity() {
        return quantity;
    }

    /**
     * Gets the shop that owns this product.
     * @return the associated shop
     */
    public Shop getShop() {
        return shop;
    }

    // SETTER METHODS

    /**
     * Sets the product price.
     * For safety and simplicity, only description and price have setters.
     * @param productPrice the new product price
     */
    public void setProductPrice(double productPrice) {
        this.productPrice = productPrice;
    }

    /**
     * Sets the product description.
     * For safety and simplicity, only description and price have setters.
     * @param productDescription the new product description
     */
    public void setProductDescription(String productDescription) {
        this.productDescription = productDescription;
    }

    /**
     * Decreases the product quantity by 1.
     * Used when a product is purchased or removed from inventory.
     */
    public void setQuantityMinus1() {
        // Decrement quantity by 1 (ensure it doesn't go below 0 in real implementation)
        this.quantity = quantity - 1;
    }
}